---
- name: Load br_netfilter for IPv4 forwarding and letting iptables see bridged traffic
  become: true
  shell: modprobe br_netfilter

- name: Set net.bridge.bridge-nf-call-iptables to 1
  become: true
  shell: echo '1' > /proc/sys/net/ipv4/ip_forward
