replicaCount: 2
storageClass:
  name: nfs
  defaultClass: true
  reclaimPolicy: Delete
  provisionerName: nfs-provisioner
  accessModes: ReadWriteOnce
  volumeBindingMode: Immediate
nfs:
  server: 192.168.88.221
  path: /volume1/kube
